networks:
  fomo-go:
    driver: bridge

services:
  Etcd:
    image: 'bitnami/etcd:latest'
    container_name: Etcd-1
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - fomo-go
  Account:
    image: ''
    container_name: Account-1
    ports:
      - "8081:8081"
    networks:
      - fomo-go
    depends_on:
      - Etcd
    environment:
      - ETCD_HOSTS=Etcd
      - PK_ENCODE_KEY=dferlopjdfertf13
      - PK_ENCODE_IV=dferlopjdfertf13
    volumes:
      - ./etcs:/app/etc
  Ws:
    image: ''
    container_name: Ws
    ports:
      - "3333:3333"
    networks:
      - fomo-go
    depends_on:
      - Etcd
    environment:
      - ETCD_HOSTS=Etcd
    volumes:
      - ./etcs:/app/etc
      - /tmp/logs/ws:/tmp/logs/ws_1

  Sol-1:
    image: ''
    container_name: Sol-1
    ports:
      - "8090:8080"
    networks:
      - fomo-go
    depends_on:
      - Ws     
      - Account
      - Etcd
    environment:
      - ETCD_HOSTS=Etcd
      - KAFKA_CA_FILE=./etc/only-4096-ca-cert
      - PK_ENCODE_KEY=dferlopjdfertf13
      - PK_ENCODE_IV=dferlopjdfertf13
    volumes:
      - ./etcs:/app/etc
      - /tmp/logs/sol_1:/tmp/logs/sol  
  Sol-2:
    image: ''
    container_name: Sol-2
    ports:
      - "8091:8080"
    networks:
      - fomo-go
    depends_on:
      - Ws
      - Account
      - Etcd
    environment:
      - ETCD_HOSTS=Etcd
      - KAFKA_CA_FILE=./etc/only-4096-ca-cert
      - PK_ENCODE_KEY=dferlopjdfertf13
      - PK_ENCODE_IV=dferlopjdfertf13
    volumes:
      - ./etcs:/app/etc
      - /tmp/logs/sol_2:/tmp/logs/sol
  App:
    image: ''
    container_name: App-1
    ports:
      - "8888:8888"
    networks:
      - fomo-go
    depends_on:
      - Sol-1
      - Account
      - Etcd
    environment:
      - ETCD_HOSTS=Etcd
    volumes:
      - ./etcs:/app/etc